document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shCore.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushBash.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushCpp.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushCSharp.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushCss.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushDelphi.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushDiff.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushGroovy.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushJava.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushJScript.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushPhp.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushPlain.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushPython.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushRuby.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushScala.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushSql.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushVb.js"></script>');
document.write('<script type="text/javascript" src="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/shBrushXml.js"></script>');
document.write('<link type="text/css" rel="stylesheet" href="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/styles/shCore.css"/>');
document.write('<link type="text/css" rel="stylesheet" href="/WebUI/Resource/Javascript/plugins/syntaxhighlighter/styles/shThemeDefault.css"/>');
document.write("<script type=\"text/javascript\">SyntaxHighlighter.config.clipboardSwf = '/WebUI/Resource/Javascript/plugins/syntaxhighlighter/scripts/clipboard.swf';SyntaxHighlighter.all();</script>");