/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "both",
                centerStage: "both",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'BK',
                            type: 'image',
                            rect: ['0px', '0px', '640px', '960px', 'auto', 'auto'],
                            opacity: '0.85365852301683',
                            fill: ["rgba(0,0,0,0)",im+"BK.png",'0px','0px']
                        },
                        {
                            id: 'zi_tao',
                            type: 'image',
                            rect: ['154px', '437px', '59px', '45px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"zi_tao.png",'0px','0px']
                        },
                        {
                            id: 'zi_0',
                            type: 'image',
                            rect: ['322px', '406px', '78px', '101px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"zi_0.png",'0px','0px'],
                            transform: [[],['-4']]
                        },
                        {
                            id: 'zi_2',
                            type: 'image',
                            rect: ['173px', '357px', '334px', '186px', 'auto', 'auto'],
                            clip: 'rect(0px 0px 186px 0px)',
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"zi_2.png",'0px','0px']
                        },
                        {
                            id: 'zi_12',
                            type: 'image',
                            rect: ['399px', '360px', '23px', '111px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"zi_1.png",'0px','0px']
                        },
                        {
                            id: 'zi_6',
                            type: 'image',
                            rect: ['423px', '401px', '78px', '111px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"zi_6.png",'0px','0px']
                        },
                        {
                            id: 'zi_shang',
                            type: 'image',
                            rect: ['439px', '299px', '47px', '81px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"zi_shang.png",'0px','0px'],
                            transform: [[],[],[],['1.94','1.94']]
                        },
                        {
                            id: 'zi_di',
                            type: 'image',
                            rect: ['194px', '604px', '275px', '66px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"zi_di.png",'0px','0px']
                        },
                        {
                            id: 'zi_yan',
                            type: 'image',
                            rect: ['246px', '387px', '9px', '9px', 'auto', 'auto'],
                            opacity: '0.85365853658537',
                            fill: ["rgba(0,0,0,0)",im+"zi_yan.png",'0px','0px']
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '640px', '960px', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,1)"]
                        }
                    }
                },
                timeline: {
                    duration: 8514,
                    autoPlay: true,
                    data: [
                        [
                            "eid90",
                            "-webkit-transform-origin",
                            3142,
                            0,
                            "linear",
                            "${zi_0}",
                            [31,96],
                            [31,96],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid352",
                            "-moz-transform-origin",
                            3142,
                            0,
                            "linear",
                            "${zi_0}",
                            [31,96],
                            [31,96],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid353",
                            "-ms-transform-origin",
                            3142,
                            0,
                            "linear",
                            "${zi_0}",
                            [31,96],
                            [31,96],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid354",
                            "msTransformOrigin",
                            3142,
                            0,
                            "linear",
                            "${zi_0}",
                            [31,96],
                            [31,96],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid355",
                            "-o-transform-origin",
                            3142,
                            0,
                            "linear",
                            "${zi_0}",
                            [31,96],
                            [31,96],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid356",
                            "transform-origin",
                            3142,
                            0,
                            "linear",
                            "${zi_0}",
                            [31,96],
                            [31,96],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid54",
                            "scaleY",
                            1978,
                            322,
                            "linear",
                            "${zi_yan}",
                            '0.37',
                            '1'
                        ],
                        [
                            "eid130",
                            "scaleY",
                            2300,
                            162,
                            "linear",
                            "${zi_yan}",
                            '1',
                            '0.81'
                        ],
                        [
                            "eid132",
                            "scaleY",
                            2462,
                            175,
                            "linear",
                            "${zi_yan}",
                            '0.81',
                            '1'
                        ],
                        [
                            "eid198",
                            "scaleY",
                            8427,
                            31,
                            "linear",
                            "${zi_yan}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid226",
                            "scaleY",
                            8458,
                            19,
                            "linear",
                            "${zi_yan}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid254",
                            "scaleY",
                            8477,
                            23,
                            "linear",
                            "${zi_yan}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid282",
                            "scaleY",
                            8500,
                            14,
                            "linear",
                            "${zi_yan}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid202",
                            "scaleY",
                            8427,
                            31,
                            "linear",
                            "${zi_di}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid230",
                            "scaleY",
                            8458,
                            19,
                            "linear",
                            "${zi_di}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid258",
                            "scaleY",
                            8477,
                            23,
                            "linear",
                            "${zi_di}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid286",
                            "scaleY",
                            8500,
                            14,
                            "linear",
                            "${zi_di}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid159",
                            "scaleX",
                            8250,
                            177,
                            "linear",
                            "${zi_shang}",
                            '1.94',
                            '1.1'
                        ],
                        [
                            "eid79",
                            "scaleX",
                            2750,
                            392,
                            "linear",
                            "${zi_0}",
                            '0.32',
                            '1'
                        ],
                        [
                            "eid191",
                            "scaleX",
                            8427,
                            31,
                            "linear",
                            "${zi_0}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid219",
                            "scaleX",
                            8458,
                            19,
                            "linear",
                            "${zi_0}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid247",
                            "scaleX",
                            8477,
                            23,
                            "linear",
                            "${zi_0}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid275",
                            "scaleX",
                            8500,
                            14,
                            "linear",
                            "${zi_0}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid201",
                            "scaleX",
                            8427,
                            31,
                            "linear",
                            "${zi_di}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid229",
                            "scaleX",
                            8458,
                            19,
                            "linear",
                            "${zi_di}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid257",
                            "scaleX",
                            8477,
                            23,
                            "linear",
                            "${zi_di}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid285",
                            "scaleX",
                            8500,
                            14,
                            "linear",
                            "${zi_di}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid200",
                            "scaleY",
                            8427,
                            31,
                            "linear",
                            "${zi_2}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid228",
                            "scaleY",
                            8458,
                            19,
                            "linear",
                            "${zi_2}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid256",
                            "scaleY",
                            8477,
                            23,
                            "linear",
                            "${zi_2}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid284",
                            "scaleY",
                            8500,
                            14,
                            "linear",
                            "${zi_2}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid8",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${zi_shang}",
                            '0',
                            '0'
                        ],
                        [
                            "eid150",
                            "opacity",
                            8250,
                            156,
                            "linear",
                            "${zi_shang}",
                            '0.000000',
                            '1'
                        ],
                        [
                            "eid123",
                            "scaleY",
                            5463,
                            1458,
                            "easeOutElastic",
                            "${zi_6}",
                            '0',
                            '1'
                        ],
                        [
                            "eid194",
                            "scaleY",
                            8427,
                            31,
                            "linear",
                            "${zi_6}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid222",
                            "scaleY",
                            8458,
                            19,
                            "linear",
                            "${zi_6}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid250",
                            "scaleY",
                            8477,
                            23,
                            "linear",
                            "${zi_6}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid278",
                            "scaleY",
                            8500,
                            14,
                            "linear",
                            "${zi_6}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid42",
                            "clip",
                            1606,
                            1031,
                            "linear",
                            "${zi_2}",
                            [0,0,186,0],
                            [0,334,186,0],
                            {valueTemplate: 'rect(@@0@@px @@1@@px @@2@@px @@3@@px)'}
                        ],
                        [
                            "eid45",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${zi_yan}",
                            '0',
                            '0'
                        ],
                        [
                            "eid126",
                            "opacity",
                            1978,
                            398,
                            "linear",
                            "${zi_yan}",
                            '0',
                            '0.85365853658537'
                        ],
                        [
                            "eid28",
                            "scaleY",
                            0,
                            691,
                            "linear",
                            "${zi_tao}",
                            '0',
                            '1.1'
                        ],
                        [
                            "eid30",
                            "scaleY",
                            691,
                            69,
                            "linear",
                            "${zi_tao}",
                            '1.1',
                            '0.99995'
                        ],
                        [
                            "eid56",
                            "scaleY",
                            760,
                            161,
                            "linear",
                            "${zi_tao}",
                            '0.99995',
                            '1.09997'
                        ],
                        [
                            "eid59",
                            "scaleY",
                            921,
                            131,
                            "linear",
                            "${zi_tao}",
                            '1.09997',
                            '1'
                        ],
                        [
                            "eid68",
                            "scaleY",
                            1051,
                            86,
                            "linear",
                            "${zi_tao}",
                            '1',
                            '1.1'
                        ],
                        [
                            "eid70",
                            "scaleY",
                            1137,
                            90,
                            "linear",
                            "${zi_tao}",
                            '1.1',
                            '1'
                        ],
                        [
                            "eid190",
                            "scaleY",
                            8427,
                            31,
                            "linear",
                            "${zi_tao}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid218",
                            "scaleY",
                            8458,
                            19,
                            "linear",
                            "${zi_tao}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid246",
                            "scaleY",
                            8477,
                            23,
                            "linear",
                            "${zi_tao}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid274",
                            "scaleY",
                            8500,
                            14,
                            "linear",
                            "${zi_tao}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid9",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${zi_di}",
                            '0',
                            '0'
                        ],
                        [
                            "eid135",
                            "opacity",
                            7182,
                            522,
                            "linear",
                            "${zi_di}",
                            '0.000000',
                            '1'
                        ],
                        [
                            "eid93",
                            "rotateZ",
                            3142,
                            300,
                            "linear",
                            "${zi_0}",
                            '0deg',
                            '10deg'
                        ],
                        [
                            "eid95",
                            "rotateZ",
                            3442,
                            201,
                            "linear",
                            "${zi_0}",
                            '10deg',
                            '-4deg'
                        ],
                        [
                            "eid97",
                            "rotateZ",
                            3643,
                            311,
                            "linear",
                            "${zi_0}",
                            '-4deg',
                            '6deg'
                        ],
                        [
                            "eid99",
                            "rotateZ",
                            3954,
                            296,
                            "linear",
                            "${zi_0}",
                            '6deg',
                            '0deg'
                        ],
                        [
                            "eid195",
                            "scaleX",
                            8427,
                            31,
                            "linear",
                            "${zi_12}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid223",
                            "scaleX",
                            8458,
                            19,
                            "linear",
                            "${zi_12}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid251",
                            "scaleX",
                            8477,
                            23,
                            "linear",
                            "${zi_12}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid279",
                            "scaleX",
                            8500,
                            14,
                            "linear",
                            "${zi_12}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid138",
                            "top",
                            7182,
                            628,
                            "linear",
                            "${zi_di}",
                            '604px',
                            '573px'
                        ],
                        [
                            "eid53",
                            "scaleX",
                            1978,
                            322,
                            "linear",
                            "${zi_yan}",
                            '0.37',
                            '1'
                        ],
                        [
                            "eid129",
                            "scaleX",
                            2300,
                            162,
                            "linear",
                            "${zi_yan}",
                            '1',
                            '0.81'
                        ],
                        [
                            "eid131",
                            "scaleX",
                            2462,
                            175,
                            "linear",
                            "${zi_yan}",
                            '0.81',
                            '1'
                        ],
                        [
                            "eid197",
                            "scaleX",
                            8427,
                            31,
                            "linear",
                            "${zi_yan}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid225",
                            "scaleX",
                            8458,
                            19,
                            "linear",
                            "${zi_yan}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid253",
                            "scaleX",
                            8477,
                            23,
                            "linear",
                            "${zi_yan}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid281",
                            "scaleX",
                            8500,
                            14,
                            "linear",
                            "${zi_yan}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid80",
                            "scaleY",
                            2750,
                            392,
                            "linear",
                            "${zi_0}",
                            '0.32',
                            '1'
                        ],
                        [
                            "eid192",
                            "scaleY",
                            8427,
                            31,
                            "linear",
                            "${zi_0}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid220",
                            "scaleY",
                            8458,
                            19,
                            "linear",
                            "${zi_0}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid248",
                            "scaleY",
                            8477,
                            23,
                            "linear",
                            "${zi_0}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid276",
                            "scaleY",
                            8500,
                            14,
                            "linear",
                            "${zi_0}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid5",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${zi_2}",
                            '0',
                            '0'
                        ],
                        [
                            "eid32",
                            "opacity",
                            1355,
                            145,
                            "linear",
                            "${zi_2}",
                            '0.000000',
                            '1'
                        ],
                        [
                            "eid115",
                            "opacity",
                            5546,
                            1228,
                            "linear",
                            "${zi_6}",
                            '0.000000',
                            '1'
                        ],
                        [
                            "eid4",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${zi_0}",
                            '0',
                            '0'
                        ],
                        [
                            "eid74",
                            "opacity",
                            2750,
                            392,
                            "linear",
                            "${zi_0}",
                            '0.000000',
                            '1'
                        ],
                        [
                            "eid160",
                            "scaleY",
                            8250,
                            177,
                            "linear",
                            "${zi_shang}",
                            '1.94',
                            '1.1'
                        ],
                        [
                            "eid10",
                            "opacity",
                            0,
                            760,
                            "linear",
                            "${zi_tao}",
                            '0.000000',
                            '1'
                        ],
                        [
                            "eid122",
                            "scaleX",
                            5463,
                            1458,
                            "easeOutElastic",
                            "${zi_6}",
                            '0',
                            '1'
                        ],
                        [
                            "eid193",
                            "scaleX",
                            8427,
                            31,
                            "linear",
                            "${zi_6}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid221",
                            "scaleX",
                            8458,
                            19,
                            "linear",
                            "${zi_6}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid249",
                            "scaleX",
                            8477,
                            23,
                            "linear",
                            "${zi_6}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid277",
                            "scaleX",
                            8500,
                            14,
                            "linear",
                            "${zi_6}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid27",
                            "scaleX",
                            0,
                            691,
                            "linear",
                            "${zi_tao}",
                            '0',
                            '1.1'
                        ],
                        [
                            "eid29",
                            "scaleX",
                            691,
                            69,
                            "linear",
                            "${zi_tao}",
                            '1.1',
                            '1'
                        ],
                        [
                            "eid60",
                            "scaleX",
                            760,
                            161,
                            "linear",
                            "${zi_tao}",
                            '1',
                            '1.1'
                        ],
                        [
                            "eid61",
                            "scaleX",
                            921,
                            131,
                            "linear",
                            "${zi_tao}",
                            '1.1',
                            '1'
                        ],
                        [
                            "eid67",
                            "scaleX",
                            1051,
                            86,
                            "linear",
                            "${zi_tao}",
                            '1',
                            '1.1'
                        ],
                        [
                            "eid69",
                            "scaleX",
                            1137,
                            90,
                            "linear",
                            "${zi_tao}",
                            '1.1',
                            '1'
                        ],
                        [
                            "eid189",
                            "scaleX",
                            8427,
                            31,
                            "linear",
                            "${zi_tao}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid217",
                            "scaleX",
                            8458,
                            19,
                            "linear",
                            "${zi_tao}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid245",
                            "scaleX",
                            8477,
                            23,
                            "linear",
                            "${zi_tao}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid273",
                            "scaleX",
                            8500,
                            14,
                            "linear",
                            "${zi_tao}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid110",
                            "top",
                            4328,
                            922,
                            "linear",
                            "${zi_12}",
                            '360px',
                            '406px'
                        ],
                        [
                            "eid199",
                            "scaleX",
                            8427,
                            31,
                            "linear",
                            "${zi_2}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid227",
                            "scaleX",
                            8458,
                            19,
                            "linear",
                            "${zi_2}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid255",
                            "scaleX",
                            8477,
                            23,
                            "linear",
                            "${zi_2}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid283",
                            "scaleX",
                            8500,
                            14,
                            "linear",
                            "${zi_2}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid6",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${zi_12}",
                            '0',
                            '0'
                        ],
                        [
                            "eid102",
                            "opacity",
                            4328,
                            922,
                            "linear",
                            "${zi_12}",
                            '0.000000',
                            '1'
                        ],
                        [
                            "eid196",
                            "scaleY",
                            8427,
                            31,
                            "linear",
                            "${zi_12}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid224",
                            "scaleY",
                            8458,
                            19,
                            "linear",
                            "${zi_12}",
                            '1.03',
                            '1'
                        ],
                        [
                            "eid252",
                            "scaleY",
                            8477,
                            23,
                            "linear",
                            "${zi_12}",
                            '1',
                            '1.03'
                        ],
                        [
                            "eid280",
                            "scaleY",
                            8500,
                            14,
                            "linear",
                            "${zi_12}",
                            '1.03',
                            '1'
                        ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("%E6%9C%AA%E5%91%BD%E5%90%8D-1_edgeActions.js");
})("EDGE-29994277");
